version: '3.8'
services:
  gateway-service:
    build:
      context: .
      dockerfile: apps/graphql-gateway/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    networks:
      - foodfund-network

  auth-service:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - "8002:8002"
      - "50001:50001"
    env_file:
      - .env.docker
    networks:
      - foodfund-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--server-response", "http://localhost:8002/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  user-service:
    build:
      context: .
      dockerfile: apps/user/Dockerfile
    ports:
      - "8003:8003"
      - "50002:50002"
    env_file:
      - .env.docker
    networks:
      - foodfund-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--server-response", "http://localhost:8003/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  foodfund-network:
    driver: bridge
