apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodfund-gateway
  namespace: foodfund-staging
  labels:
    service: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      service: gateway
  template:
    metadata:
      labels:
        service: gateway
    spec:
      containers:
        - name: gateway-service
          image: ttrece/foodfund-graphql-gateway:develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8000"
            - name: AUTH_SERVICE_URL
              value: "http://foodfund-auth-service:8002/graphql"
            - name: USER_SERVICE_URL
              value: "http://foodfund-user-service:8003/graphql"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
