apiVersion: v1
kind: Secret
metadata:
  name: foodfund-database-secret
  namespace: foodfund-staging
type: Opaque
data:
  user-database-url: "REPLACE_USER_DATABASE_URL_BASE64"
  database-host: "REPLACE_DATABASE_HOST_BASE64"
  database-port: "REPLACE_DATABASE_PORT_BASE64"
  database-username: "REPLACE_DATABASE_USERNAME_BASE64"
  database-password: "REPLACE_DATABASE_PASSWORD_BASE64"
  database-ssl-mode: "REPLACE_DATABASE_SSL_MODE_BASE64"
