apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodfund-user
  namespace: foodfund-staging
  labels:
    service: user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      containers:
        - name: user-service
          image: ttrece/foodfund-user:develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8003"
            - name: USERS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: foodfund-database-secret
                  key: user-database-url
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "150m"
